services:
  web:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: minimart
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  dbdata:
